// This file is automatically generated.

interface CssExports {
  'group': string;
  'input': string;
  'label': string;
  'sign': string;
}

declare var cssExports: CssExports;
export = cssExports;
