// This file is automatically generated.

interface CssExports {
  'content': string;
  'header': string;
  'icon-container': string;
  'iconContainer': string;
}

declare var cssExports: CssExports;
export = cssExports;
