// This file is automatically generated.

interface CssExports {
  'button': string;
  'buttons': string;
  'container': string;
  'position': string;
}

declare var cssExports: CssExports;
export = cssExports;
