// This file is automatically generated.

interface CssExports {
  'canvas': string;
  'canvas--moving': string;
  'canvasMoving': string;
  'container': string;
  'left': string;
  'navigation-button': string;
  'navigationButton': string;
  'right': string;
}

declare var cssExports: CssExports;
export = cssExports;
