// This file is automatically generated.

interface CssExports {
  'canvas': string;
  'canvas--moving': string;
  'canvasMoving': string;
  'container': string;
}

declare var cssExports: CssExports;
export = cssExports;
