// This file is automatically generated.

interface CssExports {
  'container': string;
  'controls': string;
  'tabs': string;
  'tabs--collapsed': string;
  'tabsCollapsed': string;
  'variant': string;
  'variant-detail': string;
  'variant-selection': string;
  'variant-selection__button': string;
  'variant-selection__button--disabled': string;
  'variantDetail': string;
  'variantSelection': string;
  'variantSelectionButton': string;
  'variantSelectionButtonDisabled': string;
}

declare var cssExports: CssExports;
export = cssExports;
