// This file is automatically generated.

interface CssExports {
  'button': string;
  'button--disabled': string;
  'buttonDisabled': string;
  'container': string;
  'tabs': string;
  'tabs--collapsed': string;
  'tabsCollapsed': string;
}

declare var cssExports: CssExports;
export = cssExports;
