// This file is automatically generated.

interface CssExports {
  'container': string;
  'music-group': string;
  'music-item': string;
  'musicGroup': string;
  'musicItem': string;
}

declare var cssExports: CssExports;
export = cssExports;
