// This file is automatically generated.

interface CssExports {
  'container': string;
  'detail': string;
  'detail-title': string;
  'detailTitle': string;
  'position': string;
  'selection': string;
  'selectionButton': string;
  'selectionButtonDisabled': string;
  'selection__button': string;
  'selection__button--disabled': string;
}

declare var cssExports: CssExports;
export = cssExports;
