// This file is automatically generated.

interface CssExports {
  'container': string;
  'display': string;
  'selection': string;
  'selection-button': string;
  'selectionButton': string;
}

declare var cssExports: CssExports;
export = cssExports;
