// This file is automatically generated.

interface CssExports {
  'container': string;
  'detail': string;
  'display': string;
  'display-container': string;
  'displayContainer': string;
}

declare var cssExports: CssExports;
export = cssExports;
